### PR TITLE
Added scripts to download entire playlist

### PR DESCRIPTION
**Pull request by zCri**
Tested from client side by adding the code using javascript console, not yet ran on server
This uses a different mirror to download the maps (chimu.moe) because beatconnect's api is invite-only
Some maps may not be found in the mirror, also multiple fast requests bug out the mirror apparently ([not an issue from my part](https://cdn.discordapp.com/attachments/762756409384501288/910956386953855046/unknown.png))
The beatmaps are downloaded into a zip, and missing beatmaps have a file named the beatmap id and the error inside it
p.s. update the description of the project because it also still has the old url

### CODE REVIEW

**Comment by zCri** [comment]
Oops just noticed i left some debug messages in here https://github.com/yfxu/osulist/blob/f26958f386b5410844338574280a67b3c6b9bf38/static/scripts/download-playlist.js#L14-L15, also the mirror is not optimal considering the bug, i will probably have to find another better mirror

**Comment by yfxu** [comment]
Updated the project URL. Thanks for noticing!

**Comment by yfxu** [comment]
Trying to run this branch locally but I'm getting the following error when clicking on the "Download as zip" button:
```
Uncaught TypeError: progressBar is null
    download_playlist http://localhost:5000/static/scripts/download-playlist.js:3
    onclick http://localhost:5000/p/120/:1
download-playlist.js:3:5
```

The progress bar tag does in fact exist, and it has the right ID as well. Do you know what might be causing this issue?

**Comment by zCri** [comment]
uh maybe each script is in its own scope so perhaps it would work if we assigned progressBar to the window object

**Comment by zCri** [comment]
> uh maybe each script is in its own scope so perhaps it would work if we assigned progressBar to the window object

nvm im so stupid i thought you were referring to beatmap_ids

**Comment by zCri** [comment]
Well anyways now that i read correctly id assume its because we should assign the variable on document load because it gets assigned before the page is even rendered

**Comment by yfxu** [comment]
oh wow, I was following all of this in real time but you were just faster than me at making the changes ;') The zip functionality works for me now! 

One more thing: Do you know what sorts of rate limits the Nerina mirror has? We should probably implement some kind of download timeout so as to prevent users from downloading a billion maps in a second. I'm just worried about getting ip banned loMaO. Then again I'm not sure if their server is configured to support this kind of mass downloading. Since the current max size of a playlist is 1000, we'd potentially be downloading 1000 maps sequentially. And this doesn't stop a user from downloading the same playlist in multiple different browser tabs simultaneously (I think)

**Comment by zCri** [comment]
> oh wow, I was following all of this in real time but you were just faster than me at making the changes ;') The zip functionality works for me now!
> 
> One more thing: Do you know what sorts of rate limits the Nerina mirror has? We should probably implement some kind of download timeout so as to prevent users from downloading a billion maps in a second. I'm just worried about getting ip banned loMaO. Then again I'm not sure if their server is configured to support this kind of mass downloading. Since the current max size of a playlist is 1000, we'd potentially be downloading 1000 maps sequentially. And this doesn't stop a user from downloading the same playlist in multiple different browser tabs simultaneously (I think)

i dont really know if they have a rate limit, i mean they dont even have public api docs, i just looked at the source code for the website ([its available on github](https://github.com/Nerinyan/osu-Beatmap-Mirror)) and see where the download buttons lead me to, i dont think they have any though

**Comment by yfxu** [comment]
Hmm okay I guess we'll just roll with this for now then. We could choose to respect their servers by not overloading it but if they don't have the protections put in place to begin with, then we'd only be delaying the inevitable xd.

Are there any more changes you wanted to make? If not, I'll merge this.

**Comment by zCri** [comment]
Well if it works then sure go ahead :D

**Review by yfxu — APPROVED** [review]
We can prob do some styling for the download button but later on in another PR. I'll merge for now because this is a useful feature that I think people would want.

**Comment by yfxu** [comment]
Alright, it's online now. Thanks for your help @zCri! :D

**Pull request merged**
